import { Endpoints, log } from '@shared';
import type { Method } from 'axios';
import axios from 'axios';

/**
 * The function `serviceGetAuth` is an asynchronous function that sends a POST request to a VTEX API
 * endpoint to get an authentication token using an account, API key, and API token.
 * @param {string} account - The `account` parameter is a string that represents the name of the VTEX
 * account you want to authenticate with.
 * @param {string} apiKey - The `apiKey` parameter is a string that represents the API key used for
 * authentication. It is typically a unique identifier that is associated with a specific account or
 * user.
 * @param {string} apiToken - The `apiToken` parameter is a token that is used for authentication
 * purposes. It is typically generated by the API provider and is used to verify the identity of the
 * user making the request.
 * @returns the result of the axios request.
 */
export const serviceGetAuth = async (account: string, apiKey: string, apiToken: string) => {
  try {
    if (!apiToken || !apiKey || !account) {
      log.error('no account, apiToken or apiKey');
      return;
    }

    const url = Endpoints.VTEX_GET_TOKEN(account);
    const data = JSON.stringify({
      appkey: apiKey,
      apptoken: apiToken,
    });
    const headers = {
      Referer: '',
      'Content-Type': 'application/json, application/json',
    };
    const config = {
      method: 'post' as Method,
      url,
      headers,
      data,
    };
    log.debug(config);
    return axios(config);
  } catch (error) {
    log.debug(error);
    log.error('error on get auth token');
  }
};
